package com.slack.server.workspace;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/workspace") // This means URL's start with /demo (after Application path)
public class WorkspaceController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private WorkspaceRepository workspaceRepository;

    @GetMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewWorkspace (@RequestParam String name) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Workspace n = new Workspace();
        n.setName(name);
        workspaceRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<Workspace> getAllWorkspaces() {
        // This returns a JSON or XML with the workspaces
        return workspaceRepository.findAll();
    }

    @GetMapping(path="/get")
    public @ResponseBody Workspace getWorkspaceByName(@RequestParam String name){
        return  (workspaceRepository.existsByName(name) ? workspaceRepository.findbyName(name) : null);

    }


}
